image: Ubuntu  # образ для сборки

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "18"
  
branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - yarn install

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn run build   # команда сборки

test_script:
  - yarn run lint && yarn run test  # скрипт тестирования
deploy_script: # скрипт развёртывания
- git config --global credential.helper store
- git config --global user.name AppVeyor
- git config --global user.email ci@appveyor.com
- echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
- yarn run push-dir --dir=dist --branch=gh-pages --force --verbose
